# Dependencies
markdown:         redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            'Tony Nowatzki'
tagline:          'Assistant Professor of Computer Science at UCLA <br/> Boelter 3731G'
description:      ''
url:              http://cs.ucla.ecu/~tjn
baseurl:          http://web.cs.ucla.edu/~tjn/

paginate:         1
paginate_path:    /blog/page:num

# Custom vars
version:          0.1

# Gems
gems: [jekyll-paginate]
