# Dependencies
#markdown:         redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data", "footnotes"]
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'CS251a'
tagline:          'Advanced Computer Architecture'
description:      ''
#url:              http://cs.ucla.ecu/~tjn
#baseurl:          http://web.cs.ucla.edu/~tjn/

paginate:         10
paginate_path:    /blog/page:num

# Custom vars
version:          0.1

exclude: ['*.bak']

plugins_dir: [jekyll/scholar, jekyll-gist, jekyll-paginate, github-pages]


#plugins: 
#  - jekyll/scholar
#  - jekyll-gist
#  - jekyll-paginate


